services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web

  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    environment:
      DATABASE_URL: postgresql://viplab:viplab@db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: viplab-project-algae
    depends_on:
      db:
        condition: service_healthy
    init: true
    restart: always
    networks:
      - web
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: viplab
      POSTGRES_PASSWORD: viplab
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - web
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  caddy_data:
  caddy_config:
  umami-db-data:

networks:
  web:
    driver: bridge
